### ISSUE TITLE
Block not visible to be inserted in Editor

### ISSUE THREAD

**Issue by senadir** [opr/newsletter-test#3]
The block is registered in ContactInformation section, yet I can't seem to find it when trying to insert the block.
![image](https://user-images.githubusercontent.com/6165348/131483717-3066a5c2-1b5d-4dc9-863f-f0dc43e1ce07.png)

Running this plugin with the latest trunk in Woo Blocks repo.

**Comment by opr** [comment]
Fixed with f592876fca27916b3240ab448ec8a5a826b068f9
